config/routes.rb
Rails.application.routes.draw do

  get "items/listing", to: "items#listing"

  resources :items

  devise_for :users,
  # custom added FB Callback
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: :index
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :pick_up, :drop_off, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  CATEGORIES = { "Dress" => 1, "Suit" => 2 }
  SIZES = { "XS" => 1, "S" => 2, "M" => 3, "L" => 4, "XL" => 5 }
end




  # def owner
  #   User.find(user_id)
  # end

  # def owner=(user)
  #   self.user_id = user.id
  # end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :bookings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_the_owner, only: [:edit, :update, :destroy]

  def listing
    @items = Item.all
  end

  def index
    @items = Item.all

    if params[:location].present?
      @items = @items.near(params[:location], 20)
    else
      @items = @items.where.not(latitude: nil, longitude: nil)
    end

    search_params = params.slice("category", "size")

    if !search_params.empty?
      search_params.permit!
      @items = @items.where(search_params)
    end

    @hash = Gmaps4rails.build_markers(@items) do |item, marker|
      marker.lat item.latitude
      marker.lng item.longitude
      # marker.infowindow render_to_string(partial: "/items/map_box", locals: { item: item })
    end
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.owner = current_user

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    def check_the_owner
      flash[:alert] = "You're not the owner."
      redirect_to items_path if current_user != @item.owner
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :size, :price, :latitude, :longitude, :address, :category)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to users_path
  end

  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(image)
    image || "http://placehold.it/30x30"
  end

  def item_owner_url(image)
    image || "http://saxonyfineclothing.com/wp-content/uploads/2011/03/TAILOR_1-934x1024.jpg"
  end

  def item_url(category)
    # return item.image if item.image.present?
    if category.to_i == 1
      "http://promtasticorganiser.weebly.com/uploads/1/6/7/9/16795080/7681625_orig.jpg"
    else
      "http://www.cheshireweddinguide.co.uk/wp-content/uploads/2014/11/Men_in_suits.jpg"
    end
  end
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :category, collection: Item::CATEGORIES, include_blank: false %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :size, collection: Item::SIZES, include_blank: false %>
    <%= f.input :price %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :address %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="map-wrapper">
  <div class="grid-container">
    <div class="cards_container">
      <% @items.each do |item| %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= item_url(item.category) %>');">
          <div class="card-category"></div>
          <div class="card-description">
            <h2><%= item.name %></h2>
            <p><%= item.description %></p>
            <p><%= Item::SIZES.key(item.size.to_i) %></p>
          </div>
          <img class="card-user" src="<%= item_owner_url(item.owner.facebook_picture_url) %>">
          <%= link_to "", item_path(item), class: "card-link" %>
        </div>

      <% end %>
    </div>

    <div class="map_container">
      <div id="map" style="height: 100vh"></div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/items/listing.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Size</th>
      <th>Price</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.size %></td>
        <td><%= item.price %></td>
        <td><%= item.latitude %></td>
        <td><%= item.longitude %></td>
        <td><%= item.address %></td>
        <td><%= item.category %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Size:</strong>
  <%= Item::SIZES.key(@item.size.to_i) %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @item.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @item.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @item.address %>
</p>

<p>
  <strong>Category:</strong>
  <%= Item::CATEGORIES.key(@item.category.to_i) %>
</p>

<% if current_user == @item.owner %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
<% end %>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SuitUp!DressUp!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notifications' %>

    <%= yield %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyAs5HOmj2onKhN_bw0L9MbTl_Rf5GbIqgs" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container banner" style="">
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-12 margin-form">
      <div class="text-center">
        <h1>SuitUp!</h1>
      </div>

      <h3>Look good for your special occasion</h3>
      <h3>Make money renting your closet garments</h3>

      <%= form_tag items_path, method: "get", class: "form-control input-lg" do %>
        <%= select_tag :category, options_for_select(Item::CATEGORIES) %>
        <%= select_tag :size, options_for_select(Item::SIZES) %>
        <%= text_field_tag :location, "", class: "input-lg",  placeholder: "Where?" %>

        <div class="form-group">
          <div class='input-group date datetimepicker' id='datetimepicker1'>
            <%= text_field_tag :pick_up, "", class: "input-lg",  placeholder: "Pickup date?"  %>
          </div>
          <div class='input-group date datetimepicker' id='datetimepicker2'>
            <%= text_field_tag :drop_off, "", class: "input-lg",  placeholder: "Pickup date?"  %>
          </div>
        </div>
        <%= submit_tag "Search", class: "btn btn-primary btn-lg" %>
      <% end %>

      <% content_for(:after_js) do %>
        <script type="text/javascript">
          $(function () {
            $('#datetimepicker1').datetimepicker({
              locale: 'en'
            });
          });
        </script>
      <% end %>

      <% content_for(:after_js) do %>
        <script type="text/javascript">
          $(function () {
            $('#datetimepicker2').datetimepicker({
              locale: 'en'
            });
          });
        </script>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-pinterest"></i></a>
  </div>
  <div class="footer-copyright pull-right">
    Made with <i class="fa fa-heart"></i> from your friends at Suit Up
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "bowtie.jpg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Rent a garment", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Lend a garment", new_item_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Rent a garment</a></li>
        <li><a href="#">Lend a garment</a></li>
        <li><a href="#">Message</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_notifications.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.email %></p>
  <p><%= user.first_name %></p>
  <p><%= user.last_name %></p>
<% end %>